version: '3.7'

services:
  bs_db:
    image: postgres:12
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5435:5432
  bs_web:
    build: .
    command: python /usr/src/django_project/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/django_project
    ports:
      - 8000:8000
    depends_on:
      - bs_db
volumes:
  postgres_data:
